openapi: 3.1.0
info:
  title: eth_getTransactionByHash - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
paths:
  /{apiKey}:
    post:
      summary: eth_getTransactionByHash - Polygon zkEVM
      description: Returns the information about a transaction requested by transaction hash on Polygon zkEVM. In the response object, `blockHash`, `blockNumber`, and `transactionIndex` are `null` when the transaction is pending.
      $ref: ../ethereum/eth_getTransactionByHash.yaml#/components/pathItems/path/post
      operationId: eth-gettransactionbyhash-polygon-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
        code-samples:
          - language: javascript
            name: Alchemy SDK
            code: |
              // Setup: npm install alchemy-sdk
              // Github: https://github.com/alchemyplatform/alchemy-sdk-js
              const { Alchemy, Network } = require("alchemy-sdk");

              // Optional config object, but defaults to demo api-key and eth-mainnet.
              const settings = {
                apiKey: "demo", // Replace with your Alchemy API Key.
                network: Network.POLYGONZKEVM_TESTNET, // Replace with your network.
              };
              const alchemy = new Alchemy(settings);

              alchemy.core
                .getTransaction(
                  "0x60b66de803f7bd34e40a122c30526b74914154ccba03f1f770958cccc9b59038"
                )
                .then(console.log);
