openapi: 3.1.0
info:
  title: eth_newFilter - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
          - polygonzkevm-cardona
        default: polygonzkevm-cardona
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_newFilter - Polygon zkEVM
      description: Polygon zkEVM API - Creates a filter object, based on filter options, to notify when the state changes (logs).
      $ref: ../ethereum/eth_newFilter.yaml#/components/pathItems/path/post
      operationId: eth-newfilter-polygon-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
