openapi: 3.1.0
info:
  title: eth_newBlockFilter - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_newBlockFilter - Polygon zkEVM
      description: Polygon zkEVM API - Creates a filter in the node, to notify when a new block arrives.
      $ref: ../ethereum/eth_newBlockFilter.yaml#/components/pathItems/path/post
      operationId: eth-newblockfilter-polygon-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
