openapi: 3.1.0
info:
  title: eth_getBlockByHash - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
paths:
  /{apiKey}:
    post:
      summary: eth_getBlockByHash - Polygon zkEVM
      description: Returns information about a block on Polygon zkEVM by block hash.
      $ref: ../ethereum/eth_getBlockByHash.yaml#/components/pathItems/path/post
      operationId: eth-getblockbyhash-polygon-zkevm
      x-readme:
        explorer-enable: false
        samples-languages:
          - curl
          - javascript
          - python
        code-samples:
          - language: javascript
            name: Alchemy SDK
            code: |
              // Setup: npm install alchemy-sdk
              const { Alchemy, Network } = require("alchemy-sdk");

              // Optional config object, but defaults to demo api-key and eth-mainnet.
              const settings = {
                apiKey: "demo", // Replace with your Alchemy API Key.
                network: Network.POLYGONZKEVM_TESTNET, // Replace with your network.
              };
              const alchemy = new Alchemy(settings);

              alchemy.core
                .getBlock("0x63392b0dbab8cecbf16a8174f6ee7c2fd58a01d1f9bd5599aa422d0c782908d5")
                .then(console.log);
