openapi: 3.1.0
info:
  title: eth_uninstallFilter - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_uninstallFilter - Polygon zkEVM
      description: Polygon zkEVM API - Uninstalls a filter with given id. Should always be called when watch is no longer needed. Additionally, Filters timeout when they aren not requested with `eth_getFilterChanges` for a period of time.
      $ref: ../ethereum/eth_uninstallFilter.yaml#/components/pathItems/path/post
      operationId: eth-uninstallfilter-optimism-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
