openapi: 3.1.0
info:
  title: eth_getBlockByNumber - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getBlockByNumber - Polygon zkEVM
      description: Returns information about a block on Polygon zkEVM by block number.
      operationId: eth-getblockbynumber-polygon-zkevm
      parameters:
        - $ref: ../components/parameters.yaml#/ApiKey
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/eth_getBlockByNumber_l2
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
        code-samples:
          - language: javascript
            name: Alchemy SDK
            code: |
              // Setup: npm install alchemy-sdk
              // Github: https://github.com/alchemyplatform/alchemy-sdk-js
              const { Alchemy, Network } = require("alchemy-sdk");

              // Optional config object, but defaults to demo api-key and eth-mainnet.
              const settings = {
                apiKey: "demo", // Replace with your Alchemy API Key.
                network: Network.POLYGONZKEVM_TESTNET, // Replace with your network.
              };
              const alchemy = new Alchemy(settings);

              alchemy.core.getBlock(17203429).then(console.log);
