openapi: 3.1.0
info:
  title: eth_protocolVersion - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
          - polygonzkevm-cardona
        default: polygonzkevm-cardona
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_protocolVersion - Polygon zkEVM
        description: Returns the current network protocol version as a string. Response for this method is always 0 on Polygon zkEVM.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_protocolVersion
        x-readme:
          samples-languages:
            - curl
            - javascript
            - python
        responses:
          '200':
            description: Response is always 0.
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - id
                    - jsonrpc
                    - result
                  properties:
                    id:
                      $ref: ../components/schemas.yaml#/Id
                    jsonrpc:
                      $ref: ../components/schemas.yaml#/JsonRpc
                    result:
                      type: integer
                      example: 0
        operationId: eth-protocolVersion-polygon-zkevm
