openapi: 3.1.0
info:
  title: eth_getTransactionCount - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
          - polygonzkevm-cardona
        default: polygonzkevm-cardona
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getTransactionCount - Polygon zkEVM
      description: Returns the number of transactions sent from an address on Polygon zkEVM.
      $ref: ../ethereum/eth_getTransactionCount.yaml#/components/pathItems/path/post
      operationId: eth-gettransactioncount-polygon-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
        code-samples:
          - language: javascript
            name: Alchemy SDK
            code: |
              // Setup: npm install alchemy-sdk
              // Github: https://github.com/alchemyplatform/alchemy-sdk-js
              const { Alchemy, Network } = require("alchemy-sdk");

              // Optional config object, but defaults to demo api-key and eth-mainnet.
              const settings = {
                apiKey: "demo", // Replace with your Alchemy API Key.
                network: Network.POLYGONZKEVM_TESTNET, // Replace with your network.
              };
              const alchemy = new Alchemy(settings);

              alchemy.core.getTransactionCount("0xbed9dA8f130aCC29F2580df183F3995eff78fb4D").then(console.log);
