openapi: 3.1.0
info:
  title: eth_getFilterLogs - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getFilterLogs - Polygon zkEVM
      description: Returns an array of all logs matching filter with given id on Polygon zkEVM. Can compute the same results with an eth_getLogs call.
      $ref: ../ethereum/eth_getFilterLogs.yaml#/components/pathItems/path/post
      operationId: eth-getfilterlogs-polygon-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
