openapi: 3.1.0
info:
  title: eth_getTransactionByBlockHashAndIndex - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
          - polygonzkevm-cardona
        default: polygonzkevm-cardona
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getTransactionByBlockHashAndIndex - Polygon zkEVM
      description: Returns information about a transaction by block hash and transaction index position on Polygon zkEVM.
      $ref: ../ethereum/eth_getTransactionByBlockHashAndIndex.yaml#/components/pathItems/path/post
      operationId: eth-gettransactionbyblockhashandindex-polygon-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
