openapi: 3.1.0
info:
  title: eth_getBlockTransactionCountByNumber - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getBlockTransactionCountByNumber - Polygon zkEVM
      description: Returns the number of transactions in a block matching the given block number on Polygon zkEVM.
      operationId: eth-getblocktransactioncountbynumber-polygon-zkevm
      parameters:
        - $ref: ../components/parameters.yaml#/ApiKey
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/eth_getBlockTransactionCountByNumber_l2

      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
