openapi: 3.1.0
info:
  title: net_version - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: net_version - Polygon zkEVM
      description: Returns the current network id on Polygon zkEVM.
      $ref: ../ethereum/net_version.yaml#/components/pathItems/path/post
      operationId: net-version-polygon-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
