openapi: 3.1.0
info:
  title: web3_clientVersion - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
          - polygonzkevm-cardona
        default: polygonzkevm-cardona
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: web3_clientVersion - Polygon zkEVM
      description: Returns the current client version on Polygon zkEVM.
      $ref: ../ethereum/web3_clientVersion.yaml#/components/pathItems/path/post
      operationId: web3-clientVersion-polygon-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
