openapi: 3.1.0
info:
  title: zkevm_isBlockConsolidated - Polygon zkEVM
  description: Returns true if the provided block number is already connected to a batch that was already verified, otherwise false.
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
          - polygonzkevm-cardona
        default: polygonzkevm-cardona
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        operationId: zkevm-isBlockConsolidated-polygon-zkevm
        summary: zkevm_isBlockConsolidated - Polygon zkEVM
        description: Returns true if the provided block number is already connected to a batch that was already verified, otherwise false.
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          description: Returns true if the provided block number is already connected to a batch that was already verified, otherwise false.
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/zkevm_isBlockConsolidated
        x-readme:
          samples-languages:
            - curl
            - javascript
            - python
        responses:
          '200':
            description: Returns true if the provided block number is already connected to a batch that was already verified, otherwise false.
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/zkevm_isBlockConsolidated
