openapi: 3.1.0
info:
  title: zkevm_estimateFee API - Polygon zkEVM
  description: Estimates the transaction fee based on the current gas price and transaction complexity.
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
          - polygonzkevm-cardona
        default: polygonzkevm-cardona
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        operationId: zkevm-estimateFee-polygon-zkevm
        summary: zkevm_estimateFee API - Polygon zkEVM
        description: Estimates the transaction fee following the effective gas price rules.
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: '../evm_body.yaml#/zkevm_estimateFee'
        responses:
          '200':
            description: Successfully estimated the transaction fee.
            content:
              application/json:
                schema:
                  $ref: '../evm_responses.yaml#/zkevm_estimateFee'
