openapi: 3.1.0
info:
  title: eth call - zkSync
  description: Executes a new message call immediately without creating a transaction on the blockchain.
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - zksync-mainnet
          - zksync-sepolia
        default: zksync-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        operationId: eth-call-zksync
        summary: eth_call - zkSync
        description: Executes a new message call immediately without creating a transaction on the block chain.
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          description: Accepts the transaction call object, state overrides and the block number / block hash / block tag to execute the call on.
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_call_550_gas
        x-readme:
          explorer-enabled: false
          samples-languages:
            - curl
            - javascript
            - python
        responses:
          '200':
            description: The result of the call.
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/eth_call
