openapi: 3.1.0
info:
  title: eth_getLogs - zkSync
  description: 'Returns logs which are records that denote/provide context on specific events within a smart contract, like a token transfer or a change of ownership for example.'
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - zksync-mainnet
          - zksync-sepolia
        default: zksync-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        operationId: eth-getlogs-zksync
        summary: eth_getLogs - zkSync
        description: |
          Returns an array of all logs matching a given filter object.
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_getLogs
        x-readme:
          samples-languages:
            - curl
            - javascript
            - python
        responses:
          '200':
            description: 'Returns array of log objects, or an empty array if nothing has changed since last poll.'
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/eth_getLogs
