openapi: 3.1.0
info:
  title: zks_L1ChainId - zkSync
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - zksync-mainnet
          - zksync-sepolia
        default: zksync-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: zks_L1ChainId - zkSync
        description: Returns the chain id of the underlying L1.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../evm_body.yaml#/common_request_fields'
                  - type: object
                    properties:
                      method:
                        $ref: '../components/schemas.yaml#/Method'
                        default: zks_L1ChainId
                      params:
                        type: array
                        description: No input parameters required for this method.
        responses:
          '200':
            description: The chain ID of the underlying L1.
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: '../components/zksync/schemas.yaml#/L1ChainIdResponse'
        operationId: zks-L1ChainId-zksync