openapi: 3.1.0
info:
  title: eth_getUncleByBlockHashAndIndex - Arbitrum
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - arb-mainnet
          - arb-sepolia
        default: arb-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getUncleByBlockHashAndIndex - Arbitrum
      operationId: eth-getunclebyblockhashandindex-arbitrum
      $ref: ../ethereum/eth_getUncleByBlockHashAndIndex.yaml#/components/pathItems/path/post
