openapi: 3.1.0
info:
  title: eth_getBlockTransactionCountByNumber - Arbitrum
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - arb-mainnet
          - arb-goerli
        default: arb-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getBlockTransactionCountByNumber - Arbitrum
      operationId: eth-getblocktransactioncountbynumber-arbitrum
      $ref: ../ethereum/eth_getBlockTransactionCountByNumber.yaml#/components/pathItems/path/post
