# paths in this file only work with GH actions, for command line add '../' in the beginning
openapi: 3.1.0
info:
  title: eth_getStorageAt - Arbitrum
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - arb-mainnet
          - arb-goerli
          - arb-sepolia
        default: arb-mainnet
x-sandbox:
  category:
    type:
      $ref: 'components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getStorageAt - Arbitrum
      operationId: eth-getstorageat-arbitrum
      $ref: ethereum/eth_getStorageAt.yaml#/components/pathItems/path/post
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
        code-samples:
          - language: javascript
            name: Alchemy SDK
            code: |
              // Setup: npm install alchemy-sdk
              // Github: https://github.com/alchemyplatform/alchemy-sdk-js
              import { Network, Alchemy } from "alchemy-sdk";

              // Optional config object, but defaults to demo api-key and eth-mainnet.
              const settings = {
                apiKey: "demo", // Replace with your Alchemy API Key.
                network: Network.ARB_MAINNET, // Replace with your network.
              };
              const alchemy = new Alchemy(settings);

              alchemy.core.getStorageAt("registrar.firefly.eth", 0).then(console.log);
