openapi: 3.1.0
info:
  title: net_version - Arbitrum
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - arb-mainnet
          - arb-goerli
        default: arb-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: net_version - Arbitrum
      operationId: net-version-arbitrum
      $ref: ../ethereum/net_version.yaml#/components/pathItems/path/post
