# paths in this file only work with GH actions, for command line add '../' in the beginning
openapi: 3.1.0
info:
  title: web3_sha3 - Arbitrum
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - arb-mainnet
          - arb-goerli
          - arb-sepolia
        default: arb-mainnet
x-sandbox:
  category:
    type:
      $ref: 'components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: web3_sha3 - Arbitrum
      operationId: web3-sha3-arbitrum
      $ref: ethereum/web3_sha3.yaml#/components/pathItems/path/post
