openapi: 3.1.0
info:
  title: trace_filter
  version: '1.0'
servers:
  - url: https://{network}.g.alchemy.com/v2
    variables:
      network:
        enum:
          - eth-mainnet
          - eth-sepolia
          - polygon-mainnet
          - polygon-amoy
          - arb-mainnet
          - arb-sepolia
          - opt-mainnet
          - opt-sepolia
          - base-mainnet
          - base-sepolia
        default: eth-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: trace
paths:
  /{apiKey}:
    post:
      summary: trace_filter
      description: Returns traces matching given filter.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: docs-demo
            description: |
              <style>
                .custom-style {
                  color: #048FF4;
                }
              </style>
              For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/trace_filter
      responses:
        '200':
          description: 'Returns - Array of Traces matching given filter.'
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/trace_filter
      operationId: trace-filter
