openapi: 3.1.0
info:
  title: alchemy_getTokenAllowance
  version: '1.0'
servers:
  - url: https://{network}.g.alchemy.com/v2
    variables:
      network:
        enum:
          - eth-mainnet
          - eth-sepolia
          - eth-holesky
          - zksync-mainnet
          - opt-mainnet
          - polygon-mainnet
          - polygon-amoy
          - arb-mainnet
          - arb-sepolia
          - arbnova-mainnet
          - fantom-mainnet
          - fantom-testnet
          - blast-mainnet
          - blast-sepolia
          - base-mainnet
          - base-sepolia
          - scroll-mainnet
          - scroll-sepolia
          - bnb-mainnet
          - bnb-testnet
          - avax-mainnet
          - avax-fuji
          - soneium-minato
          - geist-mainnet
          - gnosis-mainnet
          - gnosis-chiado
          - shape-mainnet
          - worldchain-mainnet
        default: eth-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: token
paths:
  /{apiKey}:
    post:
      summary: alchemy_getTokenAllowance
      description: 'Returns the amount which the spender is allowed to withdraw from the owner.'
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: docs-demo
            description: |
              <style>
                .custom-style {
                  color: #048FF4;
                }
              </style>
              For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/alchemy_getTokenAllowance
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/alchemy_getTokenAllowance
      operationId: alchemy-getTokenAllowance
