openapi: 3.1.0
info:
  title: Recent Blockhash
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - solana-mainnet
          - solana-devnet
        default: solana-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: getRecentBlockhash
      description: Returns a recent block hash from the ledger, and a fee schedule that can be used to compute the cost of submitting a transaction using it.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: docs-demo
            description: |
              <style>
                .custom-style {
                  color: #048FF4;
                }
              </style>
              For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: solana_body.yaml#/getRecentBlockhash
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: solana_responses.yaml#/getRecentBlockhash
      operationId: getRecentBlockhash
      x-readme:
        explorer-enabled: false