openapi: 3.1.0
info:
  title: alchemy_requestGasAndPaymasterAndData
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - eth-mainnet
          - eth-sepolia
          - opt-mainnet
          - polygon-mainnet
          - polygon-amoy
          - arb-mainnet
          - arb-sepolia
          - berachain-bartio
          - zora-mainnet
          - zora-sepolia
          - polynomial-mainnet
          - polynomial-sepolia
          - base-mainnet
          - base-sepolia
          - frax-mainnet
          - frax-sepolia
          - anime-sepolia
          - race-mainnet
          - shape-mainnet
          - worldchain-mainnet
        default: eth-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: gas-manager
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: alchemy_requestGasAndPaymasterAndData
        description: Requests gas and coverage for a `UserOperation`. Returns `paymasterAndData` and gas parameters if approved, errors if not. Optionally accepts fee parameter overrides to be used in the `UserOperation`.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/alchemy_requestGasAndPaymasterAndData
        x-readme:
          samples-languages:
            - curl
            - javascript
            - python
        responses:
          '200':
            description: Successful response
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/alchemy_requestGasAndPaymasterAndData
        operationId: alchemy-requestGasAndPaymasterAndData
        x-sandbox:
          category:
            type:
              $ref: '../components/sandbox.yaml#/Category'
            value: gas-manager
