openapi: 3.1.0
info:
  title: alchemy_requestFeePayer
  version: '1.0'
servers:
  - url: 'https://solana-devnet.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - solana-mainnet
          - solana-devnet
        default: solana-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: gas-manager
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: alchemy_requestFeePayer
        description: Request gas sponsorship for a `transaction` on Solana. Returns the `serializedTransaction`, including the `feePayer` signature.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/alchemy_requestFeePayer
        x-readme:
          samples-languages:
            - curl
            - javascript
            - python
        responses:
          '200':
            description: Successful response
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/alchemy_requestFeePayer
        operationId: alchemy-requestFeePayer
        x-sandbox:
          category:
            type:
              $ref: '../components/sandbox.yaml#/Category'
            value: gas-manager
