openapi: 3.1.0
info:
  title: alchemy_simulateUserOperationAssetChanges
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - eth-mainnet
          - eth-sepolia
          - arb-mainnet
          - arb-sepolia
          - opt-mainnet
          - opt-sepolia
          - polygon-mainnet
          - polygon-amoy
          - base-mainnet
          - base-sepolia
          - frax-mainnet
          - frax-sepolia
          - zora-mainnet
          - zora-sepolia
          - arbnova-mainnet
          - berachain-bartio
        default: eth-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: bundler
x-readme:
  samples-languages:
    - curl
    - javascript
    - python
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: alchemy_simulateUserOperationAssetChanges
        operationId: alchemy-simulateuseroperationassetchanges
        description: Simulates user operations and returns a list of asset changes.
        parameters:
          - $ref: ../components/parameters.yaml#/ApiKey
        requestBody:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../evm_body.yaml#/common_request_fields'
                  - type: object
                    properties:
                      method:
                        type: string
                        default: alchemy_simulateUserOperationAssetChanges
                      params:
                        type: array
                        items:
                          oneOf:
                            - $ref: '../components/schemas.yaml#/UserOperation'
                              description: User operation to simulate. Please note that the `signature` does not need to be a valid signature, only a dummy value is required similar to the one that's used for estimating gas.
                            - $ref: '../components/schemas.yaml#/EntryPoint'
                              description: EntryPoint to use for the simulation. This MUST be one of the entry points returned by the `supportedEntryPoints` RPC call.
                            - $ref: '../components/schemas.yaml#/BlockOverride'
                              description: Optional block number in context of which the simulation should be executed. If not specified, the current block number is used.
                        minItems: 3
                        maxItems: 3
                        prefixItems:
                          - $ref: '../components/schemas.yaml#/UserOperation'
                            description: User operation to simulate. Please note that the `signature` does not need to be a valid signature, only a dummy value is required similar to the one that's used for estimating gas.
                          - $ref: '../components/schemas.yaml#/EntryPoint'
                            description: EntryPoint to use for the simulation. This MUST be one of the entry points returned by the `supportedEntryPoints` RPC call.
                          - $ref: '../components/schemas.yaml#/BlockOverride'
                            description: Optional block number in context of which the simulation should be executed. If not specified, the current block number is used.
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - id
                    - jsonrpc
                    - result
                  properties:
                    id:
                      $ref: ../components/schemas.yaml#/Id
                    jsonrpc:
                      $ref: ../components/schemas.yaml#/JsonRpc
                    result:
                      $ref: '#/components/schemas/Result'

  schemas:
    Result:
      type: object
      required:
        - changes
        - error
      properties:
        changes:
          type: array
          items:
            $ref: '#/components/schemas/AssetChange'
        error:
          type: [object, 'null']
          properties:
            message:
              type: string
            revertReason:
              $ref: '#/components/schemas/RevertMessage'

    AssetChange:
      type: object
      required:
        - assetType
        - changeType
        - from
        - to
        - rawAmount
        - amount
        - symbol
        - decimals
        - contractAddress
        - name
        - logo
        - tokenId
      properties:
        assetType:
          type: string
          enum:
            - NATIVE
            - ERC20
            - ERC721
            - ERC1155
            - SPECIAL_NFT
        changeType:
          type: string
          enum:
            - APPROVE
            - TRANSFER
        from:
          $ref: '../components/schemas.yaml#/FromAddress'
        to:
          $ref: '../components/schemas.yaml#/ToAddress'
        rawAmount:
          type: string
        amount:
          type: string
        symbol:
          type: string
        decimals:
          type: [number, 'null']
        contractAddress:
          type: [string, 'null']
        name:
          type: [string, 'null']
        logo:
          type: [string, 'null']
        tokenId:
          type: [number, 'null']

    RevertMessage:
      type: string
      nullable: true
      description: >
        The reason why a transaction would revert. This provides you
        with the ability to understand the cause behind a transaction's
        potential failure before actually executing it. For example, a revert
        reason could be "ERC20: transfer amount exceeds allowance".
