openapi: 3.1.0
info:
  title: eth_sendUserOperation
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - eth-sepolia
          - eth-goerli
          - arb-goerli
          - opt-goerli
          - polygon-mumbi
        default: eth-sepolia
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_sendUserOperation
        description: Sends a user operation to the given EVM network.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_sendUserOperation
        x-readme:
          samples-languages:
            - curl
            - javascript
            - python
        responses:
          '200':
            description: Successful response
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/eth_sendUserOperation
        operationId: eth-sendUserOperation
