openapi: 3.1.0
info:
  title: 🪄 Gas Manager Admin API
  version: '1.0'
servers:
  - url: https://manage.alchemy.com/
paths:
  '/api/gas-manager/policy':
    post:
      tags: ['Gas Manager Admin API Endpoints']
      summary: Create Policy
      description: Creates a new gas manager policy with the specified rules. Returns the policy id of a successfully created policy. The newly created policy will be in the “inactive” status.
      operationId: create-policy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                app_id:
                  type: string
                  description: String ID of the app
                  default: '6d834x9k1yh4dx6z'
                rules:
                  $ref: './account-abstraction/schemas.yaml#/components/schemas/Rules' # path for using github actions, use "./schemas.yaml#/components/schemas/Rules" to update from CLI
      responses:
        '200':
          description: Policy created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      policy:
                        $ref: './account-abstraction/schemas.yaml#/components/schemas/Policy' # path for using github actions, use "./schemas.yaml#/components/schemas/Policy" to update from CLI
                  error:
                    type: object
                    properties:
                      msg:
                        type: string

  '/api/gas-manager/policy/{id}':
    get:
      tags: ['Gas Manager Admin API Endpoints']
      summary: Get Policy
      description: Returns a policy by id.
      operationId: get-policy
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            default: 'a844e221-3c13-40c6-95db-d2db390e14b5'
      responses:
        '200':
          description: Policy fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      policy:
                        $ref: './account-abstraction/schemas.yaml#/components/schemas/Policy' # path for using github actions, use "./schemas.yaml#/components/schemas/Policy" to update from CLI
                  error:
                    type: object
                    properties:
                      msg:
                        type: string

    delete:
      tags: ['Gas Manager Admin API Endpoints']
      summary: Delete Policy
      description: Deletes a policy by id.
      operationId: delete-policy
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            default: '6d834x9k1yh4dx6z'
      responses:
        '200':
          description: Policy deleted successfully

    put:
      tags: ['Gas Manager Admin API Endpoints']
      summary: Replace Policy
      description: Replaces all rules in an existing policy by id.
      operationId: replace-policy
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            default: 'a844e221-3c13-40c6-95db-d2db390e14b5'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                rules:
                  $ref: './account-abstraction/schemas.yaml#/components/schemas/Rules' # path for using github actions, use "./schemas.yaml#/components/schemas/Rules" to update from CLI
      responses:
        '200':
          description: Policy rules replaced successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      policy:
                        $ref: './account-abstraction/schemas.yaml#/components/schemas/Policy' # path for using github actions, use "./schemas.yaml#/components/schemas/Policy" to update from CLI
                  error:
                    type: object
                    properties:
                      msg:
                        type: string

  '/api/gas-manager/policies':
    get:
      tags: ['Gas Manager Admin API Endpoints']
      summary: Get All Policies
      description: Returns all policies under an app.
      operationId: get-all-policies
      parameters:
        - name: app
          in: query
          schema:
            type: string
            default: '6d834x9k1yh4dx6z'
        - name: after
          in: query
          schema:
            type: string
            format: base64url
            default: 'a844e221-3c13-40c6-95db-d2db390e14b5'
      responses:
        '200':
          description: Policies fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      policies:
                        type: array
                        items:
                          $ref: './account-abstraction/schemas.yaml#/components/schemas/Policy' # path for using github actions, use "./schemas.yaml#/components/schemas/Policy" to update from CLI
                  error:
                    type: object
                    properties:
                      msg:
                        type: string

  '/api/gas-manager/policy/{id}/status':
    put:
      tags: ['Gas Manager Admin API Endpoints']
      summary: Update Policy Status
      description: Modifies the status of a policy to either "active" or "inactive".
      operationId: update-policy-status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            default: 'a844e221-3c13-40c6-95db-d2db390e14b5'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [active, inactive]
                  default: active
      responses:
        '200':
          description: Policy status updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      policy:
                        $ref: './account-abstraction/schemas.yaml#/components/schemas/Policy' # path for using github actions, use "./schemas.yaml#/components/schemas/Policy" to update from CLI
                  error:
                    type: object
                    properties:
                      msg:
                        type: string

  '/api/gas-manager/policy/{id}/stats':
    get:
      tags: ['Gas Manager Admin API Endpoints']
      summary: Get Policy Stats
      description: Returns stats about a policy specified by ID, including signatures mined, signatures expired, signatures pending, USD mined, and USD pending.
      operationId: get-policy-stats
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            default: 'a844e221-3c13-40c6-95db-d2db390e14b5'
      responses:
        '200':
          description: Policy stats fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      signatures_mined:
                        type: integer
                        default: 10
                      signatures_expired:
                        type: integer
                        default: 1
                      signatures_pending:
                        type: integer
                        default: 1
                      usd_pending:
                        type: string
                        default: '25.03'
                      usd_mined:
                        type: string
                        default: '260.32'
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
