openapi: 3.1.0
info:
  title: rundler_maxPriorityFeePerGas
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - eth-mainnet
          - eth-sepolia
          - arb-mainnet
          - arb-sepolia
          - opt-mainnet
          - opt-sepolia
          - polygon-mainnet
          - polygon-amoy
          - base-mainnet
          - base-sepolia
        default: eth-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: bundler
paths:
  /{apiKey}:
    post:
      summary: rundler_maxPriorityFeePerGas
      description: 'Returns a fee per gas that is an estimate of how much users should set as a priority fee in UOs for Rundler endpoints.'
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: docs-demo
            description: |
              <style>
                .custom-style {
                  color: #048FF4;
                }
              </style>
              For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/rundler_maxPriorityFeePerGas
      responses:
        '200':
          description: Returns the estimated priority fee per gas to be used in UOs for Rundler endpoints.
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/string_result_response
      operationId: rundler-maxPriorityFeePerGas
      x-sandbox:
          category: Bundler
