openapi: 3.1.0
info:
  title: eth_getBlockTransactionCountByHash - Base
  version: '1.0'
servers:
  - url: https://{network}.g.alchemy.com/v2
    variables:
      network:
        enum:
          - base-mainnet
          - base-goerli
          - base-sepolia
        default: base-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getBlockTransactionCountByHash - Base
      $ref: ../ethereum/eth_getBlockTransactionCountByHash.yaml#/components/pathItems/path/post
      operationId: eth-getblocktransactioncountbyhash-base
