openapi: 3.1.0
info:
  title: eth_getBalance - Base
  version: '1.0'
servers:
  - url: https://{network}.g.alchemy.com/v2
    variables:
      network:
        enum:
          - base-mainnet
          - base-sepolia
        default: base-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getBalance - Base
      $ref: ../ethereum/eth_getBalance.yaml#/components/pathItems/path/post
      operationId: eth-getbalance-base
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
