openapi: 3.1.0
info:
  title: eth_protocolVersion - Base
  version: '1.0'
servers:
  - url: https://{network}.g.alchemy.com/v2
    variables:
      network:
        enum:
          - base-mainnet
          - base-goerli
          - base-sepolia
        default: base-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_protocolVersion - Base
      $ref: ../ethereum/eth_protocolVersion.yaml#/components/pathItems/path/post
      operationId: eth-protocolversion-base
