openapi: 3.1.0
info:
  title: OpenAPI spec used to generate SDKs 
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2'
paths:
  /{apiKey}/account/list:
    post:
      summary: eth_accounts
      operationId: accountList
      description: Returns a list of addresses owned by client. Since Alchemy does not store keys, this will always return empty.
      parameters:
        - $ref: common/auth.yml
      requestBody:
        content:
          application/json:
            schema:
              $ref: methods/eth_accounts.yml#/AccountListRequest
      responses:
        '200':
          description: Returns 20 Bytes - addresses owned by the client.
          content:
            application/json:
              schema:
                $ref: methods/eth_accounts.yml#/AccountListResponse
        

      
