openapi: 3.1.0
info:
  title: OpenAPI spec used to generate SDKs 
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2'
paths:
  /{apiKey}:
    post:
      operationId: eth-accounts
      summary: eth_accounts
      description: Returns a list of addresses owned by client. Since Alchemy does not store keys, this will always return empty.
      parameters:
        - $ref: common/auth.yml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/eth_accounts
      responses:
        '200':
          description: Returns 20 Bytes - addresses owned by the client.
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/string_result_response
        

      
