openapi: 3.1.0
info:
  title: alchemy_sendGasOptimizedTransaction
  version: '1.0'
servers:
  - url: https://{network}.g.alchemy.com/v2
    variables:
      network:
        enum:
          - eth-mainnet
          - eth-goerli
          - polygon-mainnet
          - polygon-mumbai
        default: eth-mainnet
x-readme:
  id: 634f72885e2a9200e4ebf268
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: gas-optimized-transactions
paths:
  '/{apiKey}':
    post:
      summary: alchemy_sendGasOptimizedTransaction
      description: Submits a bundle of identical transactions, each individually with a range of different gas values.
      operationId: alchemy-sendgasoptimizedtransaction
      parameters:
        - $ref: ../components/parameters.yaml#/ApiKey
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  $ref: ../components/schemas.yaml#/Id
                jsonrpc:
                  $ref: ../components/schemas.yaml#/JsonRpc
                params:
                  $ref: ../evm_body.yaml#/bundled_signed_transaction_param
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/sendTxn_result_response
