openapi: 3.1.0
info:
  title: eth_getBlockTransactionCountByNumber - Polygon PoS
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygon-mainnet
          - polygon-mumbai
          - polygon-amoy
        default: polygon-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getBlockTransactionCountByNumber - Polygon PoS
      description: Returns the number of transactions in a block matching the given block number on Polygon.
      operationId: eth-getblocktransactioncountbynumber-polygon
      parameters:
        - $ref: ../components/parameters.yaml#/ApiKey
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/eth_getBlockTransactionCountByNumber_l2
