openapi: 3.1.0
info:
  title: eth_getFilterChanges - Polygon PoS
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygon-mainnet
          - polygon-amoy
        default: polygon-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getFilterChanges - Polygon PoS
      description: 'Polling method for a filter, which returns an array of logs which occurred since last poll on Polygon.'
      $ref: ../ethereum/eth_getFilterChanges.yaml#/components/pathItems/path/post
      operationId: eth-getfilterchanges-polygon
