openapi: 3.1.0
info:
  title: eth_getBlockReceipts - Polygon PoS
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygon-mainnet
          - polygon-amoy
        default: polygon-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getBlockReceipts - Polygon PoS
      description: Get all transaction receipts for a given block on Polygon.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: docs-demo
            description: |
              <style>
                .custom-style {
                  color: #048FF4;
                }
              </style>
              For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/eth_getBlockReceipts
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/eth_getBlockReceipts
      operationId: eth-getBlockReceipts-polygon-pos
