openapi: 3.1.0
info:
  title: eth_getUncleByBlockNumberAndIndex - Polygon PoS
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygon-mainnet
          - polygon-mumbai
          - polygon-amoy
        default: polygon-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getUncleByBlockNumberAndIndex - Polygon PoS
      description: Returns information about an uncle of a block by number and uncle index position on Polygon.
      $ref: ../ethereum/eth_getUncleByBlockNumberAndIndex.yaml#/components/pathItems/path/post
      operationId: eth-getunclebyblocknumberandindex-polygon
