openapi: 3.1.0
info:
  title: net_listening - Polygon PoS
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygon-mainnet
          - polygon-mumbai
          - polygon-amoy
        default: polygon-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: net_listening - Polygon PoS
      description: Returns true if client is actively listening for network connections on Polygon.
      $ref: ../ethereum/net_listening.yaml#/components/pathItems/path/post
      operationId: net-listening-optimism
