openapi: 3.1.0
info:
  title: web3_sha3 - Polygon PoS
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygon-mainnet
          - polygon-amoy
        default: polygon-mainnet
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: web3_sha3 - Polygon PoS
      description: Returns Keccak-256 (not the standardized SHA3-256) of the given data on Polygon.
      $ref: ../ethereum/web3_sha3.yaml#/components/pathItems/path/post
      operationId: web3-sha3-polygon
