openapi: 3.1.0
info:
  title: eth_getStorageAt - Astar
  version: '1.0'
servers:
  - url: 'https://astar-mainnet.g.alchemy.com/v2'
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getStorageAt - Astar
      $ref: ../ethereum/eth_getStorageAt.yaml#/components/pathItems/path/post
      operationId: eth-getstorageat-astar
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
        code-samples:
          - language: javascript
            name: Alchemy SDK
            code: |
              // Setup: npm install alchemy-sdk
              // Github: https://github.com/alchemyplatform/alchemy-sdk-js
              import { Network, Alchemy } from "alchemy-sdk";

              // Optional config object, but defaults to demo api-key and eth-mainnet.
              const settings = {
                apiKey: "demo", // Replace with your Alchemy API Key.
                network: Network.ASTAR_MAINNET, // Replace with your network.
              };
              const alchemy = new Alchemy(settings);

              alchemy.core.getStorageAt("registrar.firefly.eth", 0).then(console.log);
