openapi: 3.1.0
info:
  title: eth_getFilterLogs - Astar
  version: '1.0'
servers:
  - url: 'https://astar-mainnet.g.alchemy.com/v2'
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getFilterLogs.yaml#/components/pathItems/path/post
      summary: eth_getFilterLogs - Astar
      operationId: eth-getfilterlogs-astar
