openapi: 3.1.0
info:
  title: eth_getBlockTransactionCountByNumber - Astar
  version: '1.0'
servers:
  - url: 'https://astar-mainnet.g.alchemy.com/v2'
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: eth_getBlockTransactionCountByNumber - Astar
      operationId: eth-getblocktransactioncountbynumber-astar
      parameters:
        - $ref: ../components/parameters.yaml#/ApiKey
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/eth_getBlockTransactionCountByNumber_l2
