openapi: 3.1.0
info:
  title: web3_sha3 - Astar
  version: '1.0'
servers:
  - url: 'https://astar-mainnet.g.alchemy.com/v2'
x-sandbox:
  category:
    type:
      $ref: '../components/sandbox.yaml#/Category'
    value: core
paths:
  /{apiKey}:
    post:
      summary: web3_sha3 - Astar
      $ref: ../ethereum/web3_sha3.yaml#/components/pathItems/path/post
      operationId: web3-sha3-astar
