# Workflow to upload APIs to docs staging environment 

name: Sync OpenAPI definition to ReadMe staging 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      # Update NFT API in docs
      - name: GitHub action to update NFT API
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi nft/nfts.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.NFT_API_ID }}
      
      # Update Notify API in docs
      - name: GitHub action to update Notify API
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi notify/notify.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.NOTIFY_API_ID }}
          
      # Update Transfers API in docs
      - name: GitHub action to update Transfers API
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi transfers/alchemy_getAssetTransfers.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.TRANSFERS_API_ID }} 

      # Update Gas Manager Admin API in docs
      - name: GitHub action to update Gas Manager Admin API
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi account-abstraction/gas_manager_admin.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.GAS_MANAGER_ADMIN_API_ID }}


      # =================================================== Update Starknet APIs in Docs ===================================================

      - name: Github action to update Starknet API - starknet_addDeclareTransaction
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_addDeclareTransaction.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_ADDDECLARETRANSACTION_ID }}

      - name: Github action to update Starknet API - starknet_getClassAt
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getClassAt.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETCLASSAT_ID }}

      - name: Github action to update Starknet API - starknet_addDeployAccountTransaction
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_addDeployAccountTransaction.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_ADDDEPLOYACCOUNTTRANSACTION_ID }}

      - name: Github action to update Starknet API - starknet_getClassHashAt
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getClassHashAt.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETCLASSHASHAT_ID }}

      - name: Github action to update Starknet API - starknet_addInvokeTransaction
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_addInvokeTransaction.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_ADDINVOKETRANSACTION_ID }}

      - name: Github action to update Starknet API - starknet_getEvents
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getEvents.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETEVENTS_ID }}

      - name: Github action to update Starknet API - starknet_blockHashAndNumber
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_blockHashAndNumber.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_BLOCKHASHANDNUMBER_ID }}

      - name: Github action to update Starknet API - starknet_getNonce
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getNonce.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETNONCE_ID }}

      - name: Github action to update Starknet API - starknet_blockNumber
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_blockNumber.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_BLOCKNUMBER_ID }}

      - name: Github action to update Starknet API - starknet_getStateUpdate
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getStateUpdate.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETSTATEUPDATE_ID }}

      - name: Github action to update Starknet API - starknet_call
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_call.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_CALL_ID }}

      - name: Github action to update Starknet API - starknet_getStorageAt
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getStorageAt.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETSTORAGEAT_ID }}

      - name: Github action to update Starknet API - starknet_chainId
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_chainId.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_CHAINID_ID }}

      - name: Github action to update Starknet API - starknet_getTransactionByBlockIdAndIndex
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getTransactionByBlockIdAndIndex.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETTRANSACTIONBYBLOCKIDANDINDEX_ID }}

      - name: Github action to update Starknet API - starknet_estimateFee
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_estimateFee.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_ESTIMATEFEE_ID }}

      - name: Github action to update Starknet API - starknet_estimateMessageFee
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_estimateMessageFee.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_ESTIMATEMESSAGEFEE_ID }}

      - name: Github action to update Starknet API - starknet_getTransactionByHash
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getTransactionByHash.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETTRANSACTIONBYHASH_ID }}

      - name: Github action to update Starknet API - starknet_getBlockTransactionCount
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getBlockTransactionCount.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETBLOCKTRANSACTIONCOUNT_ID }}

      - name: Github action to update Starknet API - starknet_getTransactionReceipt
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getTransactionReceipt.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETTRANSACTIONRECEIPT_ID }}

      - name: Github action to update Starknet API - starknet_getBlockWithTxHashes
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getBlockWithTxHashes.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETBLOCKWITHTXHASHES_ID }}

      - name: Github action to update Starknet API - starknet_pendingTransactions
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_pendingTransactions.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_PENDINGTRANSACTIONS_ID }}

      - name: Github action to update Starknet API - starknet_getBlockWithTxs
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getBlockWithTxs.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETBLOCKWITHTXS_ID }}

      - name: Github action to update Starknet API - starknet_syncing
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_syncing.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_SYNCING_ID }}

      - name: Github action to update Starknet API - starknet_getClass
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getClass.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETCLASS_ID }}

      # ====================================================================================================================================
