# Workflow to upload APIs to docs staging environment 

name: Sync OpenAPI definition to ReadMe staging 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      # Update NFT API in docs
      - name: GitHub action to update NFT API
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi nft/nfts.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.NFT_API_ID }}
      
      # Update Notify API in docs
      - name: GitHub action to update Notify API
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi notify/notify.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.NOTIFY_API_ID }}
          
      # Update Transfers API in docs
      - name: GitHub action to update Transfers API
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi transfers/alchemy_getAssetTransfers.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.TRANSFERS_API_ID }} 

      # Update Gas Manager Admin API in docs
      - name: GitHub action to update Gas Manager Admin API
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi account-abstraction/gas_manager_admin.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.GAS_MANAGER_ADMIN_API_ID }}


      # =============================================================== Update Starknet APIs in Docs ===============================================================

      - name: Github action to update Starknet API - Add Declare Transaction
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_addDeclareTransaction.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_ADDDECLARETRANSACTION_ID }}

      - name: Github action to update Starknet API - Get Class At
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getClassAt.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETCLASSAT_ID }}

      - name: Github action to update Starknet API - Add Deploy Account Transaction
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_addDeployAccountTransaction.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_ADDDEPLOYACCOUNTTRANSACTION_ID }}

      - name: Github action to update Starknet API - Get Class Hash At
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getClassHashAt.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETCLASSHASHAT_ID }}

      - name: Github action to update Starknet API - Add Invoke Transaction
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_addInvokeTransaction.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_ADDINVOKETRANSACTION_ID }}

      - name: Github action to update Starknet API - Get Events
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getEvents.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETEVENTS_ID }}

      - name: Github action to update Starknet API - Block Hash And Number
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_blockHashAndNumber.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_BLOCKHASHANDNUMBER_ID }}

      - name: Github action to update Starknet API - Get Nonce
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getNonce.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETNONCE_ID }}

      - name: Github action to update Starknet API - Block Number
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_blockNumber.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_BLOCKNUMBER_ID }}

      - name: Github action to update Starknet API - Get State Update
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getStateUpdate.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETSTATEUPDATE_ID }}

      - name: Github action to update Starknet API - Call
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_call.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_CALL_ID }}

      - name: Github action to update Starknet API - Get Storage At
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getStorageAt.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETSTORAGEAT_ID }}

      - name: Github action to update Starknet API - Chain Id
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_chainId.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_CHAINID_ID }}

      - name: Github action to update Starknet API - Get Transaction By Block Id And Index
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getTransactionByBlockIdAndIndex.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETTRANSACTIONBYBLOCKIDANDINDEX_ID }}

      - name: Github action to update Starknet API - Estimate Fee
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_estimateFee.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_ESTIMATEFEE_ID }}

      - name: Github action to update Starknet API - Get Transaction By Hash
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getTransactionByHash.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETTRANSACTIONBYHASH_ID }}

      - name: Github action to update Starknet API - Get Block Transaction Count
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getBlockTransactionCount.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETBLOCKTRANSACTIONCOUNT_ID }}

      - name: Github action to update Starknet API - Get Transaction Receipt
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getTransactionReceipt.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETTRANSACTIONRECEIPT_ID }}

      - name: Github action to update Starknet API - Get Block With Tx Hashes
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getBlockWithTxHashes.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETBLOCKWITHTXHASHES_ID }}

      - name: Github action to update Starknet API - Pending Transactions
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_pendingTransactions.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_PENDINGTRANSACTIONS_ID }}

      - name: Github action to update Starknet API - Get Block With Txs
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getBlockWithTxs.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETBLOCKWITHTXS_ID }}

      - name: Github action to update Starknet API - Syncing
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_syncing.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_SYNCING_ID }}

      - name: Github action to update Starknet API - Get Class
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi starknet/starknet_getClass.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STARKNET_GETCLASS_ID }}


      # =============================================================== Update Ethereum APIs in Docs ===============================================================

      - name: Github action to update Ethereum API - eth_createAccessList
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_createAccessList.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_CREATEACCESSLIST_ID }

      - name: Github action to update Ethereum API - eth_blockNumber
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_blockNumber.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_BLOCKNUMBER_ID }

      - name: Github action to update Ethereum API - eth_call
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_call.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_CALL_ID }

      - name: Github action to update Ethereum API - eth_accounts
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_accounts.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_ACCOUNTS_ID }

      - name: Github action to update Ethereum API - eth_newFilter
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_newFilter.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_NEWFILTER_ID }

      - name: Github action to update Ethereum API - eth_feeHistory
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_feeHistory.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_FEEHISTORY_ID }

      - name: Github action to update Ethereum API - eth_chainId
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_chainId.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_CHAINID_ID }

      - name: Github action to update Ethereum API - eth_estimateGas
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_estimateGas.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_ESTIMATEGAS_ID }

      - name: Github action to update Ethereum API - eth_gasPrice
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_gasPrice.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GASPRICE_ID }

      - name: Github action to update Ethereum API - eth_getBlockByHash
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getBlockByHash.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETBLOCKBYHASH_ID }

      - name: Github action to update Ethereum API - eth_getBlockTransactionCountByHash
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getBlockTransactionCountByHash.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETBLOCKTRANSACTIONCOUNTBYHASH_ID }

      - name: Github action to update Ethereum API - eth_getBalance
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getBalance.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETBALANCE_ID }

      - name: Github action to update Ethereum API - eth_getBlockByNumber
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getBlockByNumber.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETBLOCKBYNUMBER_ID }

      - name: Github action to update Ethereum API - eth_getBlockReceipts
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getBlockReceipts.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETBLOCKRECEIPTS_ID }

      - name: Github action to update Ethereum API - eth_getBlockTransactionCountByNumber
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getBlockTransactionCountByNumber.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETBLOCKTRANSACTIONCOUNTBYNUMBER_ID }

      - name: Github action to update Ethereum API - eth_getCode
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getCode.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETCODE_ID }

      - name: Github action to update Ethereum API - eth_getFilterChanges
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getFilterChanges.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETFILTERCHANGES_ID }

      - name: Github action to update Ethereum API - eth_getFilterLogs
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getFilterLogs.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETFILTERLOGS_ID }

      - name: Github action to update Ethereum API - eth_getLogs
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getLogs.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETLOGS_ID }

      - name: Github action to update Ethereum API - eth_getProof
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getProof.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETPROOF_ID }

      - name: Github action to update Ethereum API - eth_getStorageAt
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getStorageAt.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETSTORAGEAT_ID }

      - name: Github action to update Ethereum API - eth_getTransactionByBlockHashAndIndex
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getTransactionByBlockHashAndIndex.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETTRANSACTIONBYBLOCKHASHANDINDEX_ID }

      - name: Github action to update Ethereum API - eth_getTransactionByHash
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getTransactionByHash.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETTRANSACTIONBYHASH_ID }

      - name: Github action to update Ethereum API - eth_getTransactionCount
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getTransactionCount.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETTRANSACTIONCOUNT_ID }

      - name: Github action to update Ethereum API - eth_getTransactionReceipt
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getTransactionReceipt.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETTRANSACTIONRECEIPT_ID }

      - name: Github action to update Ethereum API - eth_getUncleByBlockHashAndIndex
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getUncleByBlockHashAndIndex.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETUNCLEBYBLOCKHASHANDINDEX_ID }

      - name: Github action to update Ethereum API - eth_getUncleByBlockNumberAndIndex
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getUncleByBlockNumberAndIndex.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETUNCLEBYBLOCKNUMBERANDINDEX_ID }

      - name: Github action to update Ethereum API - eth_getUncleCountByBlockHash
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getUncleCountByBlockHash.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETUNCLECOUNTBYBLOCKHASH_ID }

      - name: Github action to update Ethereum API - eth_getUncleCountByBlockNumber
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getUncleCountByBlockNumber.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETUNCLECOUNTBYBLOCKNUMBER_ID }

      - name: Github action to update Ethereum API - eth_maxPriorityFeePerGas
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_maxPriorityFeePerGas.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_MAXPRIORITYFEEPERGAS_ID }

      - name: Github action to update Ethereum API - eth_newBlockFilter
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_newBlockFilter.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_NEWBLOCKFILTER_ID }

      - name: Github action to update Ethereum API - eth_newPendingTransactionFilter
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_newPendingTransactionFilter.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_NEWPENDINGTRANSACTIONFILTER_ID }

      - name: Github action to update Ethereum API - eth_protocolVersion
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_protocolVersion.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_PROTOCOLVERSION_ID }

      - name: Github action to update Ethereum API - eth_sendRawTransaction
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_sendRawTransaction.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_SENDRAWTRANSACTION_ID }

      - name: Github action to update Ethereum API - eth_uninstallFilter
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_uninstallFilter.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_UNINSTALLFILTER_ID }

      - name: Github action to update Ethereum API - net_listening
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/net_listening.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_NET_LISTENING_ID }

      - name: Github action to update Ethereum API - net_version
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/net_version.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_NET_VERSION_ID }

      - name: Github action to update Ethereum API - web3_clientVersion
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/web3_clientVersion.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_WEB3_CLIENTVERSION_ID }

      - name: Github action to update Ethereum API - web3_sha3
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/web3_sha3.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_WEB3_SHA3_ID }

      - name: Github action to update Ethereum API - eth_getTransactionByBlockNumberAndIndex
        uses: readmeio/rdme@8.6.4
        with:
          rdme: openapi ethereum/eth_getTransactionByBlockNumberAndIndex.yaml --key=${ secrets.README_API_KEY } --id=${ secrets.ETHEREUM_ETH_GETTRANSACTIONBYBLOCKNUMBERANDINDEX_ID }
