name: Upload schema.json to Composer S3 bucket

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - run: npm i

      - run: npx ts-node index.ts && aws s3 cp ./output.json ${{ secrets.SCHEMA_S3_BUCKET_URL }} --cache-control no-cache
        working-directory: ./parser
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
